### ISSUE TITLE
How to increase the overlap height above 1.0f  for the stackview ???

### ISSUE THREAD

**Issue by sohanshetty** [blipinsk/FlippableStackView#5] opened 2015-09-08 09:29 UTC

**Comment by blipinsk** [comment] 2015-09-08 09:34
Duplicate of: https://github.com/blipinsk/FlippableStackView/issues/4

Please stop duplicating issues. I assure you, you won't receive the answer earlier if you keep duplicating issues.

**Closed as completed by blipinsk** 2015-09-08 09:34 UTC
Labels: Duplicate

**Comment by sohanshetty** [comment] 2015-09-08 09:36
Oh sorry desperately needed solution :( please help me out

**Comment by sohanshetty** [comment] 2015-09-08 11:54
HI blipinsk

Is it possible atleast because i'm already out of deadline now

Thank you
